CREATE TABLE
    t_leave
    (
        ID INT unsigned NOT NULL auto_increment,
        PROCESS_INSTANCE_ID VARCHAR(64),
        USER_ID VARCHAR(20) NOT NULL,
        START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON
    UPDATE
        CURRENT_TIMESTAMP,
        END_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON
    UPDATE
        CURRENT_TIMESTAMP,
        LEAVE_TYPE VARCHAR(20),
        REASON VARCHAR(2000),
        APPLY_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON
    UPDATE
        CURRENT_TIMESTAMP,
        REALITY_START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON
    UPDATE
        CURRENT_TIMESTAMP,
        REALITY_END_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON
    UPDATE
        current_timestamp,
        CONSTRAINT PK_LEAVE PRIMARY KEY (ID)
    );